name: Periodic Health Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  # schedule:
  #   - cron: '30 6 * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: full-stack-open-pokedex
    steps:
      - name: Check deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://pokedex-fso-631m.onrender.com/health
          follow-redirect: false
