name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: full-stack-open-pokedex
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Build fail notify discord
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          text: Build failed
          description: "commit \n https://github.com/${{github.repository}}/commit/${{ github.sha }} by ${{github.actor}} broke the build :("
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
          working-directory: full-stack-open-pokedex
      - name: Trigger deployment
        if: ${{github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_API_KEY}}

      - name: Deploy success notify discord
        if: ${{ github.event_name == 'push' && success() && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          text: A new version is deployed
          description: "to https://pokedex-fso-631m.onrender.com/ by ${{ github.actor}}"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


  tag_release:
    if: ${{github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}

    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: full-stack-open-pokedex
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@afe4b67b57b8ab0908e4767109a5342003639e2e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
